# Generated by Django 4.2.11 on 2024-05-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
