# Generated by Django 4.2.13 on 2024-05-17 01:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=135)),
                ('location', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=550)),
                ('video', models.CharField(max_length=550)),
                ('type', models.CharField(max_length=50)),
                ('goal', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('main_category', models.CharField(max_length=50)),
                ('main_subcat', models.CharField(max_length=50)),
                ('second_cat', models.CharField(max_length=50)),
                ('second_subcat', models.CharField(max_length=50)),
                ('launch_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('launched', models.BooleanField(default=False)),
                ('earned_today', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('project_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
