# Generated by Django 4.2.13 on 2024-05-29 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backers', '0001_initial'),
        ('rewards', '0001_initial'),
        ('projects', '0002_alter_project_user_alter_story_project_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backerreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.reward'),
        ),
        migrations.AddField(
            model_name='backer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backers', to='projects.project'),
        ),
        migrations.AddField(
            model_name='backer',
            name='rewards',
            field=models.ManyToManyField(related_name='backers', through='backers.BackerReward', to='rewards.reward'),
        ),
        migrations.AddField(
            model_name='backer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backed', to=settings.AUTH_USER_MODEL),
        ),
    ]
